// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4FNUgjwbJ6SOhdHZH4JxKgVxjAT4lxhg',
    appId: '1:753732636344:web:d7eb28bd61c11b76b2ae4d',
    messagingSenderId: '753732636344',
    projectId: 'doit-d199c',
    authDomain: 'doit-d199c.firebaseapp.com',
    storageBucket: 'doit-d199c.appspot.com',
    measurementId: 'G-Z7B7L2S9Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACYNmqaZSRvTP2yYqEu5aixGXUCIxEh1I',
    appId: '1:753732636344:android:71a758f3968319b5b2ae4d',
    messagingSenderId: '753732636344',
    projectId: 'doit-d199c',
    storageBucket: 'doit-d199c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuaH_gmhsL-6MHcWIRNhUpfThPOp0omJQ',
    appId: '1:753732636344:ios:75dd360d9cbc4609b2ae4d',
    messagingSenderId: '753732636344',
    projectId: 'doit-d199c',
    storageBucket: 'doit-d199c.appspot.com',
    iosBundleId: 'com.example.doit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuaH_gmhsL-6MHcWIRNhUpfThPOp0omJQ',
    appId: '1:753732636344:ios:e2ec7c7701c43bc7b2ae4d',
    messagingSenderId: '753732636344',
    projectId: 'doit-d199c',
    storageBucket: 'doit-d199c.appspot.com',
    iosBundleId: 'com.example.doit.RunnerTests',
  );
}
